config/routes.rb
Rails.application.routes.draw do
  get "/requests/new" => "requests#new", as: :new_request
  post "/requests" => "requests#create", as: :requests
  get "/requests/:id" => "requests#show", as: :request
  get "/requests/" => "requests#index"
  get "/requests/:id/edit" => "requests#edit", as: :edit_request
  patch "/requests/:id" => "requests#update"
  delete "/requests/:id" => "requests#destroy"

  root "requests#home"

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :department, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    request_params = params.require(:request).permit([:name, :email, :department, :message])
    @request = Request.new request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def index
    @requests = Request.all
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    request_params = params.require(:request).permit([:name, :email, :department, :message])
    @request = Request.find params[:id]
    if @request.update(request_params)
      redirect_to request_path(@request), notice: "POST UPDATED!"
    else
      render :edit
    end
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    flash[:notice] = "Request deleted successfully"
    redirect_to requests_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>"><i class="glyphicon glyphicon-home"></i> Home</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "<i class='glyphicon glyphicon-plus'></i>New Requests".html_safe, new_request_path %></li>
        <li><%= link_to "<i class='glyphicon glyphicon-plus'></i>Requests".html_safe, requests_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.0/css/bootstrap-toggle.min.css" rel="stylesheet">
  <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.0/js/bootstrap-toggle.min.js"></script>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/requests/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name%>
    <%=":" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%=":" %>
    <%= f.email_field :email  %>
  </div>
  <div>
    <%= f.label :department %>
    <%=":" %>
    <%= f.radio_button :department, "Sales", :value => "Sales" %>
    <%= label :department_sales, "Sales" %>
    <%= f.radio_button :department, "Marketing", :value => "Marketing"%>
    <%= label :department_marketing, "Marketing" %>
    <%= f.radio_button :department, "Technical", :value => "Technical" %>
    <%= label :department_technical, "Technical" %>
  </div>
  <div>
    <%= f.label :message %>
    <%= ":" %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit "Save"%>
<% end %>

app/views/requests/home.html.erb
<h1>Requests Home</h1>

app/views/requests/index.html.erb
<h1>Support Requests</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%=h request.name %></td>
    <!-- <td><%#=h request.email %></td> -->
    <td><%=h link_to request.email, request_path(request)  %></td>
    <td><%=h request.department %></td>
    <td><%=h request.message %></td>
    <td>
      <%= link_to "Edit", edit_request_path(request), class: "btn btn-warning" %>
      <%= link_to "Delete", request_path(request), method: :delete,
                                                   class: "btn btn-danger btn-sm",
                                                   data: {confirm: "Are you sure?"}%>
    </td>
    <% end %>
  </tr>
</table>

app/views/requests/new.html.erb
<%= "Supporter" %>
<hr>
<% if @request.errors.any? %>
  <ul>
    <% @request.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @request do |f| %>
  <div>
    <%= f.label :name%>
    <%=":" %>
    <%= f.text_field :name,  class: "form-control"  %>
  </div>
  <div>
    <%= f.label :email %>
    <%=":" %>
    <%= f.email_field :email,  class: "form-control"   %>
  </div>
  <div>
    <%= f.label :department %>
    <%=":" %>
    <%= f.radio_button :department, "Sales", :value => "Sales" %>
    <%= label :department_sales, "Sales" %>
    <%= f.radio_button :department, "Marketing", :value => "Marketing"%>
    <%= label :department_marketing, "Marketing" %>
    <%= f.radio_button :department, "Technical", :value => "Technical" %>
    <%= label :department_technical, "Technical" %>
  </div>
  <div>
    <%= f.label :message %>
    <%= ":" %>
    <%= f.text_area :message,  class: "form-control"  %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/requests/show.html.erb
<h1>Support Requests</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>

  <tr>
    <td><%=h @request.name %></td>
    <!-- <td><%#=h @request.email %></td> -->
    <td><%= link_to @request.email, request_path(@request) %></td>
    <td><%=h @request.department %></td>
    <td><%=h @request.message %></td>
    <td>
      <%= link_to "Edit", edit_request_path(@request), class: "btn btn-warning" %>
      <%= link_to "Delete", request_path(@request), method: :delete,
                                                    class: "btn btn-danger btn-sm",
                                                    data: {confirm: "Are you sure?"} %>
    </td>
  </tr>
</table>